version: '3.8'

services:

  db:
    container_name: db
    image: mysql:5.7  # Use the MySQL 5.7 image
    restart: always
    ports:
      - "3306:3306"  # MySQL typically uses port 3306
    environment:
      MYSQL_ROOT_PASSWORD: 12345 # Set the MySQL root password

  app:
    container_name: app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/springboot"  # Modify your database URL, e.g., jdbc:mysql://db:3306/mydb
      - "SPRING_DATASOURCE_USERNAME=root"  # Modify the MySQL username as needed
      - "SPRING_DATASOURCE_PASSWORD=12345"  # Modify the MySQL password as needed
    depends_on:
      - db
